from __future__ import annotations

from ..constants import Mirroring
from .base import Mapper, split_banks


class MMC1(Mapper):
    """Nintendo MMC1 serial mapper (iNES mapper 1)."""

    mapper_number = 1

    def __init__(self, cartridge) -> None:
        super().__init__(cartridge)
        self.shift = 0x10
        self.control = 0x0C
        self.chr_bank_0 = 0
        self.chr_bank_1 = 0
        self.prg_bank = 0
        self.prg_ram_enabled = True
        self._last_timed_write_clock: int | None = None
        self._build_cpu_code_windows()

    @property
    def mirroring(self) -> Mirroring:
        return (
            Mirroring.SINGLE_LOWER,
            Mirroring.SINGLE_UPPER,
            Mirroring.VERTICAL,
            Mirroring.HORIZONTAL,
        )[self.control & 0x03]

    @property
    def prg_banks(self) -> int:
        return max(1, len(self.cart.prg_rom) // 0x4000)

    @property
    def chr_4k_banks(self) -> int:
        return max(1, len(self.cart.chr_memory) // 0x1000)

    def _build_cpu_code_windows(self) -> None:
        """Precompose every 32 KiB PRG mapping the MMC1 registers select."""
        banks = split_banks(self.cart.prg_rom, 0x4000)
        count = len(banks)
        windows: dict[bytes, bytes] = {}
        by_key: dict[tuple[int, int], bytes] = {}
        for mode in range(4):
            for register in range(16):
                if mode in (0, 1):
                    lower = (register & 0x0E) % count
                    window = banks[lower] + banks[(lower + 1) % count]
                elif mode == 2:
                    window = banks[0] + banks[register % count]
                else:
                    window = banks[register % count] + banks[-1]
                canonical = windows.setdefault(window, window)
                by_key[(mode, register)] = canonical
        self._cpu_code_windows = tuple(windows.values())
        self._cpu_code_window_by_key = by_key

    def cpu_code_windows(self) -> tuple[bytes, ...]:
        return self._cpu_code_windows

    def cpu_code_window(self) -> bytes:
        mode = (self.control >> 2) & 0x03
        return self._cpu_code_window_by_key[(mode, self.prg_bank & 0x0F)]

    def cpu_read(self, address: int) -> int:
        if 0x6000 <= address < 0x8000:
            if self.prg_ram_enabled and self.cart.prg_ram:
                return self.cart.prg_ram[(address - 0x6000) % len(self.cart.prg_ram)]
            return 0
        if address < 0x8000:
            return 0
        return self.cpu_code_window()[address - 0x8000]

    def cpu_write(self, address: int, value: int) -> None:
        value &= 0xFF
        if 0x6000 <= address < 0x8000:
            if self.prg_ram_enabled and self.cart.prg_ram:
                self.cart.prg_ram[(address - 0x6000) % len(self.cart.prg_ram)] = value
            return
        if address < 0x8000:
            return
        if value & 0x80:
            self.shift = 0x10
            self.control |= 0x0C
            return

        complete = bool(self.shift & 1)
        self.shift = (self.shift >> 1) | ((value & 1) << 4)
        if not complete:
            return

        register_value = self.shift & 0x1F
        if address < 0xA000:
            self.control = register_value
        elif address < 0xC000:
            self.chr_bank_0 = register_value
        elif address < 0xE000:
            self.chr_bank_1 = register_value
        else:
            self.prg_bank = register_value & 0x0F
            self.prg_ram_enabled = not bool(register_value & 0x10)
        self.shift = 0x10

    def cpu_write_timed(
        self,
        address: int,
        value: int,
        cpu_clock: int,
    ) -> None:
        if address < 0x8000:
            self.cpu_write(address, value)
            return

        value &= 0xFF
        # MMC1 ignores the data bit on the second consecutive-cycle write
        # generated by a 6502 read/modify/write instruction. Reset writes
        # (bit 7) still take effect.
        if (
            not value & 0x80
            and self._last_timed_write_clock == cpu_clock
        ):
            return
        self._last_timed_write_clock = cpu_clock
        self.cpu_write(address, value)

    def _chr_offset(self, address: int) -> int:
        if self.control & 0x10:
            if address < 0x1000:
                bank = self.chr_bank_0 % self.chr_4k_banks
                return bank * 0x1000 + address
            bank = self.chr_bank_1 % self.chr_4k_banks
            return bank * 0x1000 + address - 0x1000
        bank = (self.chr_bank_0 & 0x1E) % self.chr_4k_banks
        return bank * 0x1000 + address

    def ppu_read(self, address: int) -> int:
        return self.cart.chr_memory[self._chr_offset(address) % len(self.cart.chr_memory)]

    def ppu_write(self, address: int, value: int) -> None:
        if self.cart.chr_is_ram:
            offset = self._chr_offset(address) % len(self.cart.chr_memory)
            self.cart.chr_memory[offset] = value & 0xFF

    def ppu_cache_token(self) -> tuple:
        return (
            self.control & 0x13,
            self.chr_bank_0,
            self.chr_bank_1,
        )

    def get_state(self) -> dict:
        return {
            **super().get_state(),
            "shift": self.shift,
            "control": self.control,
            "chr_bank_0": self.chr_bank_0,
            "chr_bank_1": self.chr_bank_1,
            "prg_bank": self.prg_bank,
            "prg_ram_enabled": self.prg_ram_enabled,
            "last_timed_write_clock": self._last_timed_write_clock,
        }

    def set_state(self, state: dict) -> None:
        super().set_state(state)
        self.shift = int(state["shift"])
        self.control = int(state["control"])
        self.chr_bank_0 = int(state["chr_bank_0"])
        self.chr_bank_1 = int(state["chr_bank_1"])
        self.prg_bank = int(state["prg_bank"])
        self.prg_ram_enabled = bool(state["prg_ram_enabled"])
        last_clock = state.get("last_timed_write_clock")
        self._last_timed_write_clock = (
            None if last_clock is None else int(last_clock)
        )
